### ISSUE TITLE
A Game Service is scaffolded

### ISSUE THREAD

**Issue by twist295** [KSU-SWE6813-Spring2024-Team4/swe6813#18]
This ticket involves bringing a service up that is responsible for game related backend logic and endpoints.

**Comment by elliottallmann** [comment]
https://github.com/KSU-SWE6813-Spring2024-Team4/swe6813/blob/eallmann/games-service-scaffolding/code/main_service/api/source/games.py has the basic structure here. I'm going to keep working on fleshing more of the endpoints out.
