### ISSUE TITLE
An endpoint is added for users to edit their followed game

### ISSUE THREAD

**Issue by twist295** [KSU-SWE6813-Spring2024-Team4/swe6813#21]
This ticket involves adding an endpoint to update a followed game entry (i.e. game name, hours played)

**Comment by elliottallmann** [comment]
Leaving in Ready until we figure out what we want to put in a game object.

**Comment by elliottallmann** [comment]
Moving back to Backlog, will discuss with team.

**Comment by twist295** [comment]
closing as we're descoping this based on the new prototype, please see the sprint 3 action items doc in our team files for more info!
