### ISSUE TITLE
Build GCE API server

### ISSUE THREAD

**Issue by twist295** [KSU-SWE6813-Spring2024-Team4/swe6813#5]
As an Infrastructure engineer, I would like to have at least one API server to host my APIs on. This API server will handle all of the API requests to the system's services, running each service on a different port. 

This server will be complicated because it will have all different runtimes / languages / databases installed in order to support the different services developed by different developers. 

As we develop the services, we will make note of which port each service talks over.

---

- [x] Build a new GCE server only accessible over HTTP / HTTPS from the UI server
- [x] Build places for each service to be run from, and which ports it will be run over.

**Comment by elliottallmann** [comment]
After discussion with @twist295 we're going to build the Auth service in Java Spring so I'll build with that assumption.

**Comment by elliottallmann** [comment]
As we build more services, we'll start using virtual hosts more properly. That way each service can be available via its own IP address.

**Comment by elliottallmann** [comment]
http://34.171.246.253:8080/login shows a "work in progress" message on this endpoint. Needs review but otherwise done
